# Generated by Django 5.0.14 on 2025-08-08 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_variantoption_productvariant_productvariantimage_and_more"),
    ]

    operations = []
