# Generated by Django 5.0.14 on 2026-02-02 11:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_auto_20250808_2206"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="My Wishlist", help_text="Wishlist name", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the user's default wishlist",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this wishlist is publicly visible",
                    ),
                ),
                (
                    "share_token",
                    models.CharField(
                        blank=True,
                        help_text="Token for sharing private wishlists",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this wishlist",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wishlists",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WishlistItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "variant_id",
                    models.UUIDField(
                        blank=True, help_text="Specific variant (optional)", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="User notes about this item"
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0, help_text="Priority/order within wishlist"
                    ),
                ),
                (
                    "notify_on_sale",
                    models.BooleanField(
                        default=True, help_text="Notify user when item goes on sale"
                    ),
                ),
                (
                    "notify_on_restock",
                    models.BooleanField(
                        default=True,
                        help_text="Notify user when out-of-stock item is restocked",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product in wishlist",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_items",
                        to="products.product",
                    ),
                ),
                (
                    "wishlist",
                    models.ForeignKey(
                        help_text="Parent wishlist",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="products.wishlist",
                    ),
                ),
            ],
            options={
                "db_table": "wishlist_items",
                "ordering": ["priority", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="wishlist",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("user",),
                name="unique_default_wishlist_per_user",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wishlistitem",
            unique_together={("wishlist", "product", "variant_id")},
        ),
    ]
