# Generated by Django 5.0.14 on 2026-02-01 18:20

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique order identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable order number (e.g., ORD-2024-00001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        help_text="Customer email (stored for guest orders and notifications)",
                        max_length=254,
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True, help_text="Customer phone number", max_length=20
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("product", "Product Order"),
                            ("service", "Service Order"),
                            ("booking", "Booking Order"),
                            ("mixed", "Mixed Order"),
                        ],
                        default="product",
                        help_text="Type of order",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("payment_pending", "Payment Pending"),
                            ("payment_failed", "Payment Failed"),
                            ("paid", "Paid"),
                            ("processing", "Processing"),
                            ("partially_fulfilled", "Partially Fulfilled"),
                            ("fulfilled", "Fulfilled"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Current order status",
                        max_length=30,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("authorized", "Authorized"),
                            ("paid", "Paid"),
                            ("partially_paid", "Partially Paid"),
                            ("partially_refunded", "Partially Refunded"),
                            ("refunded", "Refunded"),
                            ("voided", "Voided"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Payment status",
                        max_length=30,
                    ),
                ),
                (
                    "fulfillment_status",
                    models.CharField(
                        choices=[
                            ("unfulfilled", "Unfulfilled"),
                            ("partially_fulfilled", "Partially Fulfilled"),
                            ("fulfilled", "Fulfilled"),
                            ("scheduled", "Scheduled"),
                        ],
                        db_index=True,
                        default="unfulfilled",
                        help_text="Fulfillment status",
                        max_length=30,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency code (ISO 4217)",
                        max_length=3,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Subtotal before discounts, tax, shipping",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "discount_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total discount amount",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "tax_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total tax amount",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "shipping_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total shipping cost",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Final total amount",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount paid so far",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "amount_refunded",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount refunded",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "billing_address",
                    models.JSONField(
                        blank=True, default=dict, help_text="Billing address snapshot"
                    ),
                ),
                (
                    "shipping_address",
                    models.JSONField(
                        blank=True, default=dict, help_text="Shipping address snapshot"
                    ),
                ),
                (
                    "placed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When order was placed (checkout completed)",
                        null=True,
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, help_text="When payment was confirmed", null=True
                    ),
                ),
                (
                    "fulfilled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When order was fully fulfilled",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When order was completed", null=True
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, help_text="When order was cancelled", null=True
                    ),
                ),
                (
                    "customer_notes",
                    models.TextField(blank=True, help_text="Notes from customer"),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes (not visible to customer)"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="web",
                        help_text="Order source (web, mobile, api, admin)",
                        max_length=50,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of order placement", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User agent string"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Customer who placed the order (null for guest checkout)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("product", "Product"),
                            ("service", "Service"),
                            ("booking", "Booking"),
                            ("fee", "Fee"),
                            ("discount", "Discount"),
                        ],
                        default="product",
                        help_text="Type of line item",
                        max_length=20,
                    ),
                ),
                (
                    "product_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Reference to product (if product item)",
                        null=True,
                    ),
                ),
                (
                    "variant_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Reference to product variant (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "service_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Reference to service (if service item)",
                        null=True,
                    ),
                ),
                (
                    "booking_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Reference to booking (if booking item)",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Item name (snapshot)", max_length=500),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True, help_text="SKU (snapshot)", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Item description"),
                ),
                (
                    "variant_options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Variant options snapshot (e.g., {size: 'M', color: 'Blue'})",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Unit price at time of order",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="Quantity ordered"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Discount on this item",
                        max_digits=12,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Tax on this item",
                        max_digits=12,
                    ),
                ),
                (
                    "quantity_fulfilled",
                    models.PositiveIntegerField(
                        default=0, help_text="Quantity fulfilled so far"
                    ),
                ),
                (
                    "fulfillment_status",
                    models.CharField(
                        choices=[
                            ("unfulfilled", "Unfulfilled"),
                            ("partially_fulfilled", "Partially Fulfilled"),
                            ("fulfilled", "Fulfilled"),
                            ("scheduled", "Scheduled"),
                        ],
                        default="unfulfilled",
                        help_text="Item fulfillment status",
                        max_length=30,
                    ),
                ),
                (
                    "requires_shipping",
                    models.BooleanField(
                        default=True, help_text="Whether this item requires shipping"
                    ),
                ),
                (
                    "is_digital",
                    models.BooleanField(
                        default=False, help_text="Whether this is a digital item"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional item metadata"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Parent order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "order_items",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderNote",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(help_text="Note content")),
                (
                    "is_customer_visible",
                    models.BooleanField(
                        default=False, help_text="Whether customer can see this note"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "order_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True, help_text="Previous status", max_length=30
                    ),
                ),
                ("to_status", models.CharField(help_text="New status", max_length=30)),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Reason for status change"),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made the change",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Order status histories",
                "db_table": "order_status_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_number"], name="orders_order_n_1336be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer", "status"], name="orders_custome_58f6c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "created_at"], name="orders_status_11db6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["payment_status"], name="orders_payment_050188_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["fulfillment_status"], name="orders_fulfill_2fe79c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["placed_at"], name="orders_placed__34697f_idx"),
        ),
    ]
