# Generated by Django 5.0.14 on 2025-07-26 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (unique)", max_length=100, unique=True
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly category identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Category description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Category image",
                        null=True,
                        upload_to="categories/",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether category is active"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category for hierarchy",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "db_table": "categories",
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="categories_slug_b4303a_idx"),
                    models.Index(
                        fields=["parent"], name="categories_parent__7983b2_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="categories_is_acti_aae090_idx"
                    ),
                    models.Index(
                        fields=["sort_order"], name="categories_sort_or_77e69f_idx"
                    ),
                ],
            },
        ),
    ]
