# Generated by Django 5.0.14 on 2026-02-01 18:20

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Service name", max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=255, unique=True
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True, help_text="Brief service summary", max_length=500
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed service description"),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="Service tags for filtering"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Service status",
                        max_length=20,
                    ),
                ),
                (
                    "pricing_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed Price"),
                            ("hourly", "Per Hour"),
                            ("daily", "Per Day"),
                            ("custom", "Custom Quote"),
                            ("free", "Free"),
                        ],
                        default="fixed",
                        help_text="How service is priced",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Service price (interpretation depends on pricing_type)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "compare_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Original price (for discounts)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency code (ISO 4217)",
                        max_length=3,
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=60, help_text="Service duration in minutes"
                    ),
                ),
                (
                    "buffer_before_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Buffer time before service"
                    ),
                ),
                (
                    "buffer_after_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Buffer time after service"
                    ),
                ),
                (
                    "max_attendees",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum attendees per session (1 for 1-on-1)",
                    ),
                ),
                (
                    "min_attendees",
                    models.PositiveIntegerField(
                        default=1, help_text="Minimum attendees to confirm booking"
                    ),
                ),
                (
                    "requires_booking",
                    models.BooleanField(
                        default=True, help_text="Whether service requires booking"
                    ),
                ),
                (
                    "advance_booking_days",
                    models.PositiveIntegerField(
                        default=30, help_text="How many days in advance can book"
                    ),
                ),
                (
                    "min_notice_hours",
                    models.PositiveIntegerField(
                        default=24, help_text="Minimum notice hours for booking"
                    ),
                ),
                (
                    "cancellation_policy",
                    models.TextField(blank=True, help_text="Cancellation policy text"),
                ),
                (
                    "free_cancellation_hours",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="Hours before service for free cancellation",
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        help_text="Featured service image",
                        null=True,
                        upload_to="services/",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, help_text="SEO meta title", max_length=255
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, help_text="SEO meta description"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "services",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceAddon",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Add-on name", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Add-on description"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Additional price",
                        max_digits=12,
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Additional duration in minutes"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addons",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "db_table": "service_addons",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Category name", max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Category description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Category image",
                        null=True,
                        upload_to="service_categories/",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether category is active"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category for hierarchy",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="services.servicecategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Service categories",
                "db_table": "service_categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Service category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="services.servicecategory",
            ),
        ),
        migrations.CreateModel(
            name="ServiceImage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Service image", upload_to="services/gallery/"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alternative text for accessibility",
                        max_length=255,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "db_table": "service_images",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceProvider",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Whether this is the primary provider"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether provider is active for this service",
                    ),
                ),
                (
                    "custom_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Custom price for this provider (overrides service price)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "custom_duration",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Custom duration for this provider (overrides service duration)",
                        null=True,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Provider bio for this service"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="Service they provide",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="providers",
                        to="services.service",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Staff user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_providers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "service_providers",
                "ordering": ["-is_primary", "user__first_name"],
            },
        ),
        migrations.AddIndex(
            model_name="servicecategory",
            index=models.Index(fields=["slug"], name="service_cat_slug_192b5a_idx"),
        ),
        migrations.AddIndex(
            model_name="servicecategory",
            index=models.Index(
                fields=["is_active"], name="service_cat_is_acti_c27f89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["slug"], name="services_slug_ffd546_idx"),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["status"], name="services_status_6676e7_idx"),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["category", "status"], name="services_categor_e16510_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["pricing_type"], name="services_pricing_ee4783_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="serviceprovider",
            unique_together={("user", "service")},
        ),
    ]
