# Generated by Django 5.0.14 on 2026-02-01 18:20

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilitySchedule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Default Schedule",
                        help_text="Schedule name for management",
                        max_length=100,
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        blank=True,
                        help_text="When this schedule starts (null = always)",
                        null=True,
                    ),
                ),
                (
                    "effective_until",
                    models.DateField(
                        blank=True,
                        help_text="When this schedule ends (null = indefinite)",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        help_text="Provider this schedule applies to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_schedules",
                        to="services.serviceprovider",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        help_text="Service this schedule applies to (if no provider specified)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_schedules",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "db_table": "availability_schedules",
                "ordering": ["-is_active", "name"],
            },
        ),
        migrations.CreateModel(
            name="BlockedTime",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Reason for block (e.g., 'Vacation', 'Lunch Break')",
                        max_length=100,
                    ),
                ),
                ("start_datetime", models.DateTimeField(help_text="Block start time")),
                ("end_datetime", models.DateTimeField(help_text="Block end time")),
                (
                    "is_all_day",
                    models.BooleanField(
                        default=False, help_text="Whether this blocks the entire day"
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False, help_text="Whether this block repeats"
                    ),
                ),
                (
                    "recurrence_rule",
                    models.CharField(
                        blank=True,
                        help_text="iCal RRULE string for recurring blocks",
                        max_length=255,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_times",
                        to="services.serviceprovider",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_times",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "db_table": "blocked_times",
                "ordering": ["start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        editable=False,
                        help_text="Human-readable booking reference",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(db_index=True, help_text="Booking start time"),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(db_index=True, help_text="Booking end time"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "attendee_count",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of attendees"
                    ),
                ),
                (
                    "attendee_names",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of attendee names for group bookings",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per attendee at booking time",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total booking price",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "addons",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of add-on IDs and prices at booking time",
                    ),
                ),
                (
                    "customer_notes",
                    models.TextField(blank=True, help_text="Notes from customer"),
                ),
                (
                    "internal_notes",
                    models.TextField(blank=True, help_text="Internal staff notes"),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancellation_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("customer_request", "Customer Request"),
                            ("provider_unavailable", "Provider Unavailable"),
                            ("schedule_conflict", "Schedule Conflict"),
                            ("weather", "Weather"),
                            ("emergency", "Emergency"),
                            ("no_show", "No Show"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("cancellation_notes", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer who made the booking",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="orders.order",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        help_text="Provider assigned to this booking",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="services.serviceprovider",
                    ),
                ),
                (
                    "rescheduled_from",
                    models.ForeignKey(
                        blank=True,
                        help_text="Original booking if this is a reschedule",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rescheduled_to",
                        to="bookings.booking",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="Service being booked",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "db_table": "bookings",
                "ordering": ["-start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="BookingStatusHistory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="bookings.booking",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "booking_status_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AvailabilitySlot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ],
                        help_text="Day of week (1=Monday, 7=Sunday)",
                    ),
                ),
                ("start_time", models.TimeField(help_text="Slot start time")),
                ("end_time", models.TimeField(help_text="Slot end time")),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="bookings.availabilityschedule",
                    ),
                ),
            ],
            options={
                "db_table": "availability_slots",
                "ordering": ["day_of_week", "start_time"],
                "unique_together": {("schedule", "day_of_week", "start_time")},
            },
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["reference"], name="bookings_referen_54e5a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["customer", "status"], name="bookings_custome_b789e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["provider", "start_datetime"],
                name="bookings_provide_b8498f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["service", "start_datetime"], name="bookings_service_b9d465_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["status", "start_datetime"], name="bookings_status_3fed1f_idx"
            ),
        ),
    ]
