# Generated by Django 5.0.14 on 2025-08-05 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_emailverificationtoken_passwordresettoken_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
