# Generated by Django 5.0.14 on 2026-02-02 12:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("vendor", "Vendor"),
                    ("staff", "Staff"),
                    ("admin", "Admin"),
                    ("super_admin", "Super Admin"),
                ],
                default="customer",
                help_text="User role",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("store_name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("store_description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="vendors/logos/"
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True, null=True, upload_to="vendors/banners/"
                    ),
                ),
                (
                    "vendor_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual Seller"),
                            ("business", "Business"),
                            ("service_provider", "Service Provider"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        blank=True, help_text="Legal business name", max_length=255
                    ),
                ),
                (
                    "business_registration_number",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        help_text="Tax identification number",
                        max_length=100,
                    ),
                ),
                ("business_email", models.EmailField(blank=True, max_length=254)),
                ("business_phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state_province", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="Ethiopia", max_length=100)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("documents_required", "Documents Required"),
                            ("under_review", "Under Review"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(
                        blank=True, help_text="Admin notes on verification"
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Platform commission percentage",
                        max_digits=5,
                    ),
                ),
                ("payout_method", models.CharField(blank=True, max_length=50)),
                ("payout_details", models.JSONField(blank=True, default=dict)),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Can the vendor sell?"
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("accepts_returns", models.BooleanField(default=True)),
                ("return_policy", models.TextField(blank=True)),
                ("shipping_policy", models.TextField(blank=True)),
                ("total_products", models.PositiveIntegerField(default=0)),
                ("total_orders", models.PositiveIntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_vendors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "vendors",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("store_name", models.CharField(max_length=255)),
                (
                    "vendor_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual Seller"),
                            ("business", "Business"),
                            ("service_provider", "Service Provider"),
                        ],
                        max_length=20,
                    ),
                ),
                ("business_description", models.TextField()),
                (
                    "product_categories",
                    models.JSONField(
                        default=list, help_text="Categories vendor plans to sell in"
                    ),
                ),
                ("expected_monthly_sales", models.CharField(blank=True, max_length=50)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application",
                        to="authentication.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "vendor_applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("id_front", "ID Card (Front)"),
                            ("id_back", "ID Card (Back)"),
                            ("business_license", "Business License"),
                            ("tax_certificate", "Tax Certificate"),
                            ("bank_statement", "Bank Statement"),
                            ("other", "Other Document"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file", models.FileField(upload_to="vendors/documents/")),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="authentication.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "vendor_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["verification_status"], name="vendors_verific_3efd2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(fields=["is_active"], name="vendors_is_acti_04b085_idx"),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(fields=["slug"], name="vendors_slug_5bb22c_idx"),
        ),
    ]
