# Generated by Django 5.0.14 on 2026-02-01 18:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventOutbox",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of event (e.g., order.created)",
                        max_length=50,
                    ),
                ),
                (
                    "aggregate_type",
                    models.CharField(
                        help_text="Type of entity (e.g., Order, Booking)", max_length=50
                    ),
                ),
                (
                    "aggregate_id",
                    models.CharField(help_text="ID of the entity", max_length=36),
                ),
                ("payload", models.JSONField(help_text="Event data payload")),
                ("is_processed", models.BooleanField(db_index=True, default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("max_retries", models.PositiveIntegerField(default=5)),
                ("last_error", models.TextField(blank=True)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "event_outbox",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_processed", "created_at"],
                        name="event_outbo_is_proc_be791f_idx",
                    ),
                    models.Index(
                        fields=["event_type", "is_processed"],
                        name="event_outbo_event_t_0ab49a_idx",
                    ),
                    models.Index(
                        fields=["aggregate_type", "aggregate_id"],
                        name="event_outbo_aggrega_36deb8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("order.created", "Order Created"),
                            ("order.confirmed", "Order Confirmed"),
                            ("order.paid", "Order Paid"),
                            ("order.processing", "Order Processing"),
                            ("order.shipped", "Order Shipped"),
                            ("order.delivered", "Order Delivered"),
                            ("order.cancelled", "Order Cancelled"),
                            ("order.refunded", "Order Refunded"),
                            ("booking.created", "Booking Created"),
                            ("booking.confirmed", "Booking Confirmed"),
                            ("booking.reminder", "Booking Reminder"),
                            ("booking.cancelled", "Booking Cancelled"),
                            ("booking.rescheduled", "Booking Rescheduled"),
                            ("booking.completed", "Booking Completed"),
                            ("booking.no_show", "Booking No Show"),
                            ("payment.received", "Payment Received"),
                            ("payment.failed", "Payment Failed"),
                            ("payment.refund", "Refund Processed"),
                            ("service.published", "Service Published"),
                            ("service.updated", "Service Updated"),
                            ("system.announcement", "System Announcement"),
                            ("system.maintenance", "System Maintenance"),
                            ("user.welcome", "Welcome"),
                            ("user.password_changed", "Password Changed"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Notification title", max_length=255),
                ),
                ("message", models.TextField(help_text="Notification message body")),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional data payload"
                    ),
                ),
                (
                    "action_url",
                    models.URLField(
                        blank=True, help_text="URL for the notification action"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "channels_sent",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Channels through which notification was sent",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When notification expires and should be hidden",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User this notification is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_a4dd5c_idx",
                    ),
                    models.Index(
                        fields=["user", "notification_type"],
                        name="notificatio_user_id_63f199_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="notificatio_user_id_7336fd_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("order.created", "Order Created"),
                            ("order.confirmed", "Order Confirmed"),
                            ("order.paid", "Order Paid"),
                            ("order.processing", "Order Processing"),
                            ("order.shipped", "Order Shipped"),
                            ("order.delivered", "Order Delivered"),
                            ("order.cancelled", "Order Cancelled"),
                            ("order.refunded", "Order Refunded"),
                            ("booking.created", "Booking Created"),
                            ("booking.confirmed", "Booking Confirmed"),
                            ("booking.reminder", "Booking Reminder"),
                            ("booking.cancelled", "Booking Cancelled"),
                            ("booking.rescheduled", "Booking Rescheduled"),
                            ("booking.completed", "Booking Completed"),
                            ("booking.no_show", "Booking No Show"),
                            ("payment.received", "Payment Received"),
                            ("payment.failed", "Payment Failed"),
                            ("payment.refund", "Refund Processed"),
                            ("service.published", "Service Published"),
                            ("service.updated", "Service Updated"),
                            ("system.announcement", "System Announcement"),
                            ("system.maintenance", "System Maintenance"),
                            ("user.welcome", "Welcome"),
                            ("user.password_changed", "Password Changed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("websocket_enabled", models.BooleanField(default=True)),
                ("email_enabled", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=False)),
                ("push_enabled", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_preferences",
                "unique_together": {("user", "notification_type")},
            },
        ),
    ]
